#!/bin/bash
# program take file name and check file permission
if test $# -ne 1
then
	echo "Required 1 parameter"
	exit 1
fi

if test -f $1
then
	if [ -w $1 -a -r $1 -a -x $1 ]; then
		echo "File have permission rwx"
	else 
		echo "File haven't permission rwx"
	fi
else
	echo "Not a file"
fi
